### ISSUE TITLE
Archive a student project in zenodo

### ISSUE THREAD

**Issue by jurra** [Robotic-Building-TU-Delft/dcc-collab#4]
# Purpose
- Evaluate Zenodo vs 4TU, compare which one better seves research practices.
- [Do a feature comparison and see what are the advantages

**Comment by MaxLatour** [comment]
@jurra I'm encountering a problem in Zenodo as well as in 4TU. I've prepared a draft archive to publish, but certain information needs to be provided by Vera or Henriette. Is there a way to share the unpublished archive so we can edit it together?

**Comment by jurra** [comment]
@MaxLatour my only solution would be to share this entire folder in surfdrive, gdrive or dropbox.

**Comment by jurra** [comment]
I see now that figshare has a projects option, maybe we can try that: [https://help.figshare.com/article/how-to-use-projects-and-collaborate-on-figshare](https://help.figshare.com/article/how-to-use-projects-and-collaborate-on-figshare)

**Comment by jurra** [comment]
I also just checked and projects are not enabled in the 4TU. So I would go to the previous plan of surfdrive. These platforms are mostly developed to archive things by one person. Figshare provides a project feature, but I think it is disabled at 4TU.

**Comment by MaxLatour** [comment]
Well, the data itself is ready, the issue is the metadata. I could collect the data by sending an email, but I thought there might be a way to do this collectively.
